version: '2'
services:
    moocyourlife-app:
        image: moocyourlife
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://moocyourlife-postgresql:5432/moocyourlife
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    moocyourlife-postgresql:
        extends:
            file: postgresql.yml
            service: moocyourlife-postgresql
